// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxypdtihtsgispqwummd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4eXBkdGlodHNnaXNwcXd1bW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0Mjk0MDgsImV4cCI6MjA5MDAwNTQwOH0.-kVRrcOZDSdZYRiHFstcqe5ZKfGd1Tav7xkQrNexW9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});